version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_katapult
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: application_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "9090:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_katapult
    environment:
      PMA_HOST: mysql_katapult
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql-data:
